import json
import os
import re
import shutil
from os.path import join
from unittest import TestCase, mock

import click
import httpretty
import pytest
from click.testing import CliRunner

from rsconnect import VERSION
from rsconnect.api import RSConnectClient, RSConnectServer
from rsconnect.json_web_token import SECRET_KEY_ENV
from rsconnect.main import cli, env_management_callback

from .utils import (
    apply_common_args,
    get_api_path,
    get_dir,
    get_manifest_path,
    has_jwt_structure,
    optional_ca_data,
    optional_target,
    require_api_key,
    require_connect,
    require_connect_version,
)


def _error_to_response(error):
    """
    HTTPretty is unable to show errors resulting from callbacks, so this method attempts to raise failure visibility by
    passing the return back through HTTP.
    """
    return [555, {}, str(error)]


def _load_json(data):
    if isinstance(data, bytes):
        return json.loads(data.decode())
    return json.loads(data)


class TestMain:
    def setup_method(self):
        # Isolate from any real ``~/.rsconnect-python/`` on the host.
        # ``teardown_method`` restores ``HOME`` so the relative path does not
        # leak into later tests that invoke ``uv`` and would otherwise create
        # ``<cwd>/test-home/.cache/uv/`` inside their working directory.
        self._saved_home = os.environ.get("HOME")
        shutil.rmtree("test-home", ignore_errors=True)
        os.environ["HOME"] = "test-home"

    def teardown_method(self):
        if self._saved_home is None:
            os.environ.pop("HOME", None)
        else:
            os.environ["HOME"] = self._saved_home
        shutil.rmtree("test-home", ignore_errors=True)

    @staticmethod
    def optional_target(default):
        return os.environ.get("CONNECT_DEPLOY_TARGET", default)

    @staticmethod
    def optional_ca_data(default=None):
        # noinspection SpellCheckingInspection
        return os.environ.get("CONNECT_CADATA_FILE", default)

    # noinspection SpellCheckingInspection
    def create_deploy_args(self, deploy_command, target):
        connect_server = require_connect()
        api_key = require_api_key()
        cadata_file = optional_ca_data(None)
        args = ["deploy", deploy_command]
        apply_common_args(args, server=connect_server, key=api_key, cacert=cadata_file)
        args.append(target)
        return args

    def test_version(self):
        runner = CliRunner()
        result = runner.invoke(cli, ["version"])
        assert result.exit_code == 0, result.output
        assert VERSION in result.output

    def test_ping(self):
        connect_server = require_connect()
        runner = CliRunner()
        result = runner.invoke(cli, ["details", "-s", connect_server])
        assert result.exit_code == 0, result.output
        assert "OK" in result.output

    def test_ping_api_key(self):
        connect_server = require_connect()
        api_key = require_api_key()
        runner = CliRunner()
        args = ["details"]
        apply_common_args(args, server=connect_server, key=api_key)
        result = runner.invoke(cli, args)
        assert result.exit_code == 0, result.output
        assert "OK" in result.output

    def test_deploy(self):
        require_connect_version("2025.03.0")
        target = optional_target(get_dir(join("pip1", "dummy.ipynb")))
        runner = CliRunner()
        args = self.create_deploy_args("notebook", target)
        result = runner.invoke(cli, args)
        assert result.exit_code == 0, result.output

    @pytest.mark.parametrize(
        "command, target,expected_activate",
        [
            args + [flag]
            for flag in [True, False]
            for args in [
                ["notebook", get_dir(join("pip1", "dummy.ipynb"))],
                ["html", get_manifest_path("pyshiny_with_manifest", "")],
                ["manifest", get_manifest_path("pyshiny_with_manifest", "")],
                ["quarto", get_manifest_path("pyshiny_with_manifest", "")],
                ["tensorflow", get_api_path("pyshiny_with_manifest", "")],
                ["voila", get_dir(join("pip1", "dummy.ipynb"))],
                # This covers all deploys generated by generate_deploy_python
                ["fastapi", get_api_path("stock-api-fastapi", "")],
            ]
        ],
    )
    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_deploy_draft(self, command, target, expected_activate, caplog):
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)

        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/server_settings",
            body=json.dumps({"version": "9999.99.99"}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/user",
            body=open("tests/testdata/connect-responses/me.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        # Mock v1/content search for unique name checking
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/content?name=app5",
            body=json.dumps([]),  # Empty array means name is available
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content",
            body=json.dumps(
                {
                    "id": "1234",
                    "guid": "1234-5678-9012-3456",
                    "title": "app5",
                    "content_url": "http://fake_server/content/1234-5678-9012-3456",
                    "dashboard_url": "http://fake_server/connect/#/apps/1234-5678-9012-3456",
                }
            ),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.PATCH,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456",
            body=json.dumps(
                {
                    "id": "1234",
                    "guid": "1234-5678-9012-3456",
                    "title": "app5",
                    "content_url": "http://fake_server/content/1234-5678-9012-3456",
                    "dashboard_url": "http://fake_server/connect/#/apps/1234-5678-9012-3456",
                }
            ),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/applications/1234-5678-9012-3456",
            body=json.dumps(
                {
                    "id": "1234-5678-9012-3456",
                    "guid": "1234-5678-9012-3456",
                    "title": "app5",
                    "url": "http://fake_server/apps/1234-5678-9012-3456",
                }
            ),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456",
            body=json.dumps(
                {
                    "id": "1234",
                    "guid": "1234-5678-9012-3456",
                    "title": "app5",
                    "content_url": "http://fake_server/content/1234-5678-9012-3456",
                    "dashboard_url": "http://fake_server/connect/#/apps/1234-5678-9012-3456",
                }
            ),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456/bundles",
            body=json.dumps(
                {
                    "id": "FAKE_BUNDLE_ID",
                }
            ),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        # This is the important part for the draft deployment
        # We can check that the process actually submits the draft
        deploy_api_invoked = []

        def post_application_deploy_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            expectation = {"bundle_id": "FAKE_BUNDLE_ID"}
            if not expected_activate:
                expectation["activate"] = False
            assert parsed_request == expectation
            deploy_api_invoked.append(True)
            return [201, {"Content-Type": "application/json"}, json.dumps({"task_id": "FAKE_TASK_ID"})]

        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456/deploy",
            body=post_application_deploy_callback,
        )

        # Fake deploy task completion
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/tasks/FAKE_TASK_ID?wait=1",
            body=json.dumps({"output": ["FAKE_OUTPUT"], "last": "FAKE_LAST", "finished": True, "code": 0}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/applications/1234-5678-9012-3456/config",
            body=json.dumps({}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456",
            body=json.dumps(
                {
                    "dashboard_url": "http://fake_server/connect/#/apps/1234-5678-9012-3456",
                }
            ),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        expected_content_url = "http://fake_server/content/1234-5678-9012-3456"
        expected_draft_url = "http://fake_server/connect/#/apps/1234-5678-9012-3456/draft/FAKE_BUNDLE_ID"
        try:
            runner = CliRunner()
            args = apply_common_args(["deploy", command, target], server="http://fake_server", key="FAKE_API_KEY")
            args.append("--no-verify")
            if not expected_activate:
                args.append("--draft")
            with mock.patch("rsconnect.main.which_quarto", return_value=None), mock.patch(
                "rsconnect.main.quarto_inspect", return_value={}
            ), mock.patch(
                # Do not validate app mode, so that the "target" content doesn't matter.
                "rsconnect.api.RSConnectExecutor.validate_app_mode",
                new=lambda self_, *args, **kwargs: self_,
            ), caplog.at_level("INFO"):
                result = runner.invoke(cli, args)
            assert result.exit_code == 0, result.output
            assert deploy_api_invoked == [True]
            assert "Deployment completed successfully." in caplog.text
            if expected_activate:
                assert f"Direct content URL: {expected_content_url}" in caplog.text
            else:
                assert f"Draft content URL: {expected_draft_url}" in caplog.text
        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_deploy_verify_before_activate(self, caplog):
        # Without --draft or --no-verify, the default flow deploys the bundle as a
        # draft (activate=false), verifies the draft bundle's preview URL, and only
        # then activates it. The active bundle should never receive an unverified build.
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)

        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/server_settings",
            body=json.dumps({"version": "9999.99.99"}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/user",
            body=open("tests/testdata/connect-responses/me.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/content?name=app5",
            body=json.dumps([]),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        content_body = json.dumps(
            {
                "id": "1234",
                "guid": "1234-5678-9012-3456",
                "title": "app5",
                "content_url": "http://fake_server/content/1234-5678-9012-3456",
                "dashboard_url": "http://fake_server/connect/#/apps/1234-5678-9012-3456",
            }
        )
        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content",
            body=content_body,
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456",
            body=content_body,
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456/bundles",
            body=json.dumps({"id": "FAKE_BUNDLE_ID"}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        # Record the body of each deploy call so we can assert the draft-then-activate
        # ordering.
        deploy_bodies = []

        def post_application_deploy_callback(request, uri, response_headers):
            deploy_bodies.append(_load_json(request.body))
            return [201, {"Content-Type": "application/json"}, json.dumps({"task_id": "FAKE_TASK_ID"})]

        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456/deploy",
            body=post_application_deploy_callback,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/tasks/FAKE_TASK_ID?wait=1",
            body=json.dumps({"output": ["FAKE_OUTPUT"], "last": "FAKE_LAST", "finished": True, "code": 0}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        # The verify step accesses the draft bundle's preview URL. A 200 confirms it runs.
        verify_invoked = []

        def get_bundle_preview_callback(request, uri, response_headers):
            verify_invoked.append(uri)
            return [200, {"Content-Type": "text/html"}, "<html></html>"]

        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/content/1234-5678-9012-3456/_bundleFAKE_BUNDLE_ID/",
            body=get_bundle_preview_callback,
        )

        try:
            runner = CliRunner()
            args = apply_common_args(
                ["deploy", "manifest", get_manifest_path("pyshiny_with_manifest", "")],
                server="http://fake_server",
                key="FAKE_API_KEY",
            )
            with mock.patch(
                "rsconnect.api.RSConnectExecutor.validate_app_mode",
                new=lambda self_, *args, **kwargs: self_,
            ), caplog.at_level("INFO"):
                result = runner.invoke(cli, args)
            assert result.exit_code == 0, result.output
            # First deploy is a draft, then verify, then a second deploy that activates it.
            assert deploy_bodies == [
                {"bundle_id": "FAKE_BUNDLE_ID", "activate": False},
                {"bundle_id": "FAKE_BUNDLE_ID"},
            ]
            assert len(verify_invoked) == 1
            assert "Verifying deployed content..." in caplog.text
            assert "Activating deployed content..." in caplog.text
        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_deploy_verify_before_activate_unsupported_server(self, caplog):
        # Servers older than 2025.06.0 reject the "activate" field, so we must not deploy
        # a draft. Instead we deploy + activate in one step (no "activate" field sent) and
        # verify the active content, as before draft support existed.
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)

        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/server_settings",
            body=json.dumps({"version": "2025.03.0"}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/user",
            body=open("tests/testdata/connect-responses/me.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/content?name=app5",
            body=json.dumps([]),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        content_body = json.dumps(
            {
                "id": "1234",
                "guid": "1234-5678-9012-3456",
                "title": "app5",
                "content_url": "http://fake_server/content/1234-5678-9012-3456",
                "dashboard_url": "http://fake_server/connect/#/apps/1234-5678-9012-3456",
            }
        )
        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content",
            body=content_body,
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456",
            body=content_body,
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456/bundles",
            body=json.dumps({"id": "FAKE_BUNDLE_ID"}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        deploy_bodies = []

        def post_application_deploy_callback(request, uri, response_headers):
            deploy_bodies.append(_load_json(request.body))
            return [201, {"Content-Type": "application/json"}, json.dumps({"task_id": "FAKE_TASK_ID"})]

        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456/deploy",
            body=post_application_deploy_callback,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/tasks/FAKE_TASK_ID?wait=1",
            body=json.dumps({"output": ["FAKE_OUTPUT"], "last": "FAKE_LAST", "finished": True, "code": 0}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        # On an old server the verify step hits the *active* content URL, not a draft.
        verify_invoked = []

        def get_active_content_callback(request, uri, response_headers):
            verify_invoked.append(uri)
            return [200, {"Content-Type": "text/html"}, "<html></html>"]

        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/content/1234-5678-9012-3456/",
            body=get_active_content_callback,
        )

        try:
            runner = CliRunner()
            args = apply_common_args(
                ["deploy", "manifest", get_manifest_path("pyshiny_with_manifest", "")],
                server="http://fake_server",
                key="FAKE_API_KEY",
            )
            with mock.patch(
                "rsconnect.api.RSConnectExecutor.validate_app_mode",
                new=lambda self_, *args, **kwargs: self_,
            ), caplog.at_level("INFO"):
                result = runner.invoke(cli, args)
            assert result.exit_code == 0, result.output
            # A single deploy that activates immediately: no "activate" field is sent,
            # and there is no second (activation) deploy call.
            assert deploy_bodies == [{"bundle_id": "FAKE_BUNDLE_ID"}]
            # The active content was verified, and nothing was separately activated.
            assert len(verify_invoked) == 1
            assert "Verifying deployed content..." in caplog.text
            assert "Activating deployed content..." not in caplog.text
        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_deploy_draft_unsupported_server(self):
        # --draft cannot be honored on servers that reject the "activate" field, and
        # silently activating would be the opposite of the user's intent, so the deploy
        # fails with a clear error instead of sending an unsupported request.
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)

        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/server_settings",
            body=json.dumps({"version": "2025.03.0"}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/user",
            body=open("tests/testdata/connect-responses/me.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/content?name=app5",
            body=json.dumps([]),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        # The deploy endpoint must never be called: we should fail before sending it.
        deploy_invoked = []

        def post_application_deploy_callback(request, uri, response_headers):
            deploy_invoked.append(uri)
            return [201, {"Content-Type": "application/json"}, json.dumps({"task_id": "FAKE_TASK_ID"})]

        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456/deploy",
            body=post_application_deploy_callback,
        )

        try:
            runner = CliRunner()
            args = apply_common_args(
                ["deploy", "manifest", "--draft", get_manifest_path("pyshiny_with_manifest", "")],
                server="http://fake_server",
                key="FAKE_API_KEY",
            )
            with mock.patch(
                "rsconnect.api.RSConnectExecutor.validate_app_mode",
                new=lambda self_, *args, **kwargs: self_,
            ):
                result = runner.invoke(cli, args)
            assert result.exit_code != 0
            assert "Deploying as a draft requires Posit Connect 2025.06.0 or later." in result.output
            assert deploy_invoked == []
        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_deploy_bundle(self, caplog):
        # Deploying a downloaded bundle should upload the tarball as-is (no
        # re-bundling) and run the standard Connect deploy flow.
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)

        bundle_path = join("tests", "testdata", "bundle.tar.gz")
        with open(bundle_path, "rb") as f:
            original_bundle_bytes = f.read()

        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/server_settings",
            body=json.dumps({"version": "9999.99.99"}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/user",
            body=open("tests/testdata/connect-responses/me.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        # Unique-name check: the bundle's title defaults to "app", so the name
        # derived from it is "app", which is available.
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/content?name=app",
            body=json.dumps([]),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        content_body = json.dumps(
            {
                "id": "1234",
                "guid": "1234-5678-9012-3456",
                "title": "app",
                "content_url": "http://fake_server/content/1234-5678-9012-3456",
                "dashboard_url": "http://fake_server/connect/#/apps/1234-5678-9012-3456",
            }
        )
        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content",
            body=content_body,
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.PATCH,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456",
            body=content_body,
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456",
            body=content_body,
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        # Capture the uploaded bundle to verify it is uploaded unchanged.
        uploaded_bundle = []

        def post_bundle_callback(request, uri, response_headers):
            uploaded_bundle.append(request.body)
            return [200, {"Content-Type": "application/json"}, json.dumps({"id": "FAKE_BUNDLE_ID"})]

        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456/bundles",
            body=post_bundle_callback,
        )

        deploy_api_invoked = []

        def post_application_deploy_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            assert parsed_request == {"bundle_id": "FAKE_BUNDLE_ID"}
            deploy_api_invoked.append(True)
            return [201, {"Content-Type": "application/json"}, json.dumps({"task_id": "FAKE_TASK_ID"})]

        httpretty.register_uri(
            httpretty.POST,
            "http://fake_server/__api__/v1/content/1234-5678-9012-3456/deploy",
            body=post_application_deploy_callback,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://fake_server/__api__/v1/tasks/FAKE_TASK_ID?wait=1",
            body=json.dumps({"output": ["FAKE_OUTPUT"], "last": "FAKE_LAST", "finished": True, "code": 0}),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        try:
            runner = CliRunner()
            args = apply_common_args(["deploy", "bundle", bundle_path], server="http://fake_server", key="FAKE_API_KEY")
            args.append("--no-verify")
            with caplog.at_level("INFO"):
                result = runner.invoke(cli, args)
            assert result.exit_code == 0, result.output
            assert deploy_api_invoked == [True]
            assert "Deployment completed successfully." in caplog.text
            # The bundle was uploaded as-is: the original tarball bytes appear
            # unchanged within the (chunk-encoded) upload body.
            assert len(uploaded_bundle) == 1
            assert original_bundle_bytes in uploaded_bundle[0]
        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value

    # noinspection SpellCheckingInspection
    @pytest.mark.skip(reason="Skipping R manifest test (requires R 3.5, docker containers have moved on).")
    def test_deploy_manifest(self):
        target = optional_target(get_manifest_path("shinyapp"))
        runner = CliRunner()
        args = self.create_deploy_args("manifest", target)
        result = runner.invoke(cli, args)
        assert result.exit_code == 0, result.output

    # noinspection SpellCheckingInspection
    @httpretty.activate(verbose=True, allow_net_connect=False)
    @mock.patch("rsconnect.api.webbrowser.open_new")
    def test_deploy_manifest_shinyapps(self, mock_open_browser):
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)

        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/users/me",
            body=open("tests/testdata/rstudio-responses/get-user.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/applications"
            "?filter=name:like:shinyapp&offset=0&count=100&use_advanced_filters=true",
            body=open("tests/testdata/rstudio-responses/get-applications.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/accounts/",
            body=open("tests/testdata/rstudio-responses/get-accounts.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        def post_application_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            try:
                assert parsed_request == {"account": 82069, "name": "myapp", "template": "shiny"}
            except AssertionError as e:
                return _error_to_response(e)
            return [
                201,
                {"Content-Type": "application/json"},
                open("tests/testdata/rstudio-responses/application.json", "r").read(),
            ]

        httpretty.register_uri(
            httpretty.POST,
            "https://api.shinyapps.io/v1/applications/",
            body=post_application_callback,
            status=200,
        )

        def post_application_property_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            try:
                assert parsed_request == {"value": "private"}
            except AssertionError as e:
                return _error_to_response(e)
            return [
                201,
                {},
                b"",
            ]

        httpretty.register_uri(
            httpretty.PUT,
            "https://api.shinyapps.io/v1/applications/8442/properties/application.visibility",
            body=post_application_property_callback,
            status=200,
        )

        def post_bundle_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            del parsed_request["checksum"]
            del parsed_request["content_length"]
            try:
                assert parsed_request == {
                    "application": 8442,
                    "content_type": "application/x-tar",
                }
            except AssertionError as e:
                return _error_to_response(e)
            return [
                201,
                {"Content-Type": "application/json"},
                open("tests/testdata/rstudio-responses/create-bundle.json", "r").read(),
            ]

        httpretty.register_uri(
            httpretty.POST,
            "https://api.shinyapps.io/v1/bundles",
            body=post_bundle_callback,
        )

        httpretty.register_uri(
            httpretty.PUT,
            "https://lucid-uploads-staging.s3.amazonaws.com/bundles/application-8442/"
            "6c9ed0d91ee9426687d9ac231d47dc83.tar.gz"
            "?AWSAccessKeyId=theAccessKeyId"
            "&Signature=dGhlU2lnbmF0dXJlCg%3D%3D"
            "&content-md5=D1blMI4qTiI3tgeUOYXwkg%3D%3D"
            "&content-type=application%2Fx-tar"
            "&x-amz-security-token=dGhlVG9rZW4K"
            "&Expires=1656715153",
            body="",
        )

        def post_bundle_status_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            try:
                assert parsed_request == {"status": "ready"}
            except AssertionError as e:
                return _error_to_response(e)
            return [303, {"Location": "https://api.shinyapps.io/v1/bundles/12640"}, ""]

        httpretty.register_uri(
            httpretty.POST,
            "https://api.shinyapps.io/v1/bundles/12640/status",
            body=post_bundle_status_callback,
        )

        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/bundles/12640",
            body=open("tests/testdata/rstudio-responses/get-accounts.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        def post_deploy_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            try:
                assert parsed_request == {"bundle": 12640, "rebuild": False}
            except AssertionError as e:
                return _error_to_response(e)
            return [
                303,
                {"Location": "https://api.shinyapps.io/v1/tasks/333"},
                open("tests/testdata/rstudio-responses/post-deploy.json", "r").read(),
            ]

        httpretty.register_uri(
            httpretty.POST,
            "https://api.shinyapps.io/v1/applications/8442/deploy",
            body=post_deploy_callback,
        )

        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/tasks/333",
            body=open("tests/testdata/rstudio-responses/get-task.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        runner = CliRunner()
        args = [
            "deploy",
            "manifest",
            get_manifest_path("shinyapp"),
            "--account",
            "some-account",
            "--token",
            "someToken",
            "--secret",
            "c29tZVNlY3JldAo=",
            "--title",
            "myApp",
            "--visibility",
            "private",
        ]
        try:
            result = runner.invoke(cli, args)
            assert result.exit_code == 0, result.output
        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value

    @httpretty.activate(verbose=True, allow_net_connect=False)
    @mock.patch("rsconnect.api.webbrowser.open_new")
    def test_redeploy_manifest_shinyapps(self, mock_open_browser):
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)

        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/users/me",
            body=open("tests/testdata/rstudio-responses/get-user.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/applications"
            "?filter=name:like:shinyapp&offset=0&count=100&use_advanced_filters=true",
            body=open("tests/testdata/rstudio-responses/get-applications.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/accounts/",
            body=open("tests/testdata/rstudio-responses/get-accounts.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/applications/8442",
            body=open("tests/testdata/rstudio-responses/application.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        def post_application_property_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            try:
                assert parsed_request == {"value": "private"}
            except AssertionError as e:
                return _error_to_response(e)
            return [
                201,
                {},
                b"",
            ]

        httpretty.register_uri(
            httpretty.PUT,
            "https://api.shinyapps.io/v1/applications/8442/properties/application.visibility",
            body=post_application_property_callback,
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        def post_bundle_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            del parsed_request["checksum"]
            del parsed_request["content_length"]
            try:
                assert parsed_request == {
                    "application": 8442,
                    "content_type": "application/x-tar",
                }
            except AssertionError as e:
                return _error_to_response(e)
            return [
                201,
                {"Content-Type": "application/json"},
                open("tests/testdata/rstudio-responses/create-bundle.json", "r").read(),
            ]

        httpretty.register_uri(
            httpretty.POST,
            "https://api.shinyapps.io/v1/bundles",
            body=post_bundle_callback,
        )

        httpretty.register_uri(
            httpretty.PUT,
            "https://lucid-uploads-staging.s3.amazonaws.com/bundles/application-8442/"
            "6c9ed0d91ee9426687d9ac231d47dc83.tar.gz"
            "?AWSAccessKeyId=theAccessKeyId"
            "&Signature=dGhlU2lnbmF0dXJlCg%3D%3D"
            "&content-md5=D1blMI4qTiI3tgeUOYXwkg%3D%3D"
            "&content-type=application%2Fx-tar"
            "&x-amz-security-token=dGhlVG9rZW4K"
            "&Expires=1656715153",
            body="",
        )

        def post_bundle_status_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            try:
                assert parsed_request == {"status": "ready"}
            except AssertionError as e:
                return _error_to_response(e)
            return [303, {"Location": "https://api.shinyapps.io/v1/bundles/12640"}, ""]

        httpretty.register_uri(
            httpretty.POST,
            "https://api.shinyapps.io/v1/bundles/12640/status",
            body=post_bundle_status_callback,
        )

        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/bundles/12640",
            body=open("tests/testdata/rstudio-responses/get-accounts.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        def post_deploy_callback(request, uri, response_headers):
            parsed_request = _load_json(request.body)
            try:
                assert parsed_request == {"bundle": 12640, "rebuild": False}
            except AssertionError as e:
                return _error_to_response(e)
            return [
                303,
                {"Location": "https://api.shinyapps.io/v1/tasks/333"},
                open("tests/testdata/rstudio-responses/post-deploy.json", "r").read(),
            ]

        httpretty.register_uri(
            httpretty.POST,
            "https://api.shinyapps.io/v1/applications/8442/deploy",
            body=post_deploy_callback,
        )

        httpretty.register_uri(
            httpretty.GET,
            "https://api.shinyapps.io/v1/tasks/333",
            body=open("tests/testdata/rstudio-responses/get-task.json", "r").read(),
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        runner = CliRunner()
        args = [
            "deploy",
            "manifest",
            get_manifest_path("shinyapp"),
            "--account",
            "some-account",
            "--token",
            "someToken",
            "--secret",
            "c29tZVNlY3JldAo=",
            "--title",
            "myApp",
            "--visibility",
            "private",
            "--app-id",
            "8442",
        ]
        try:
            result = runner.invoke(cli, args)
            assert result.exit_code == 0, result.output
        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value

    def test_deploy_api(self):
        require_connect_version("2025.03.0")
        target = optional_target(get_api_path("flask"))
        runner = CliRunner()
        args = self.create_deploy_args("api", target)
        result = runner.invoke(cli, args)
        assert result.exit_code == 0, result.output

    def test_deploy_api_fail_verify(self):
        target = optional_target(get_api_path("flask-bad"))
        runner = CliRunner()
        args = self.create_deploy_args("api", target)
        args.extend(["-e", "badapp"])
        result = runner.invoke(cli, args)
        assert result.exit_code == 1, result.output

    def test_deploy_api_fail_no_verify(self):
        require_connect_version("2025.03.0")
        target = optional_target(get_api_path("flask-bad"))
        runner = CliRunner()
        args = self.create_deploy_args("api", target)
        args.extend(["--no-verify", "-e", "badapp"])
        result = runner.invoke(cli, args)
        assert result.exit_code == 0, result.output

    @staticmethod
    def _deployed_content_guid(caplog):
        # The deploy flow logs "Direct content URL: <server>/content/<guid>".
        match = re.search(r"/content/([0-9a-fA-F-]+)", caplog.text)
        assert match is not None, "Could not find deployed content URL in:\n" + caplog.text
        return match.group(1)

    def test_default_deploy_does_not_activate_broken_bundle(self, caplog):
        # #769: the default flow deploys a draft, verifies it, and only then activates
        # it. A broken redeploy must fail AND leave the previously-active (working)
        # bundle serving. Without verify-before-activate, the broken bundle is activated
        # before verification, so the active bundle becomes the broken one.
        # Draft deploys (the activate field) require Connect 2025.06.0+.
        require_connect_version("2025.06.0")
        client = RSConnectClient(RSConnectServer(require_connect(), require_api_key()))
        runner = CliRunner()

        # 1. Deploy a working app. It is verified and becomes the active bundle.
        with caplog.at_level("INFO"):
            good = runner.invoke(cli, self.create_deploy_args("api", get_api_path("flask")))
        assert good.exit_code == 0, good.output
        guid = self._deployed_content_guid(caplog)
        good_bundle_id = client.content_get(guid)["bundle_id"]
        assert good_bundle_id is not None

        # 2. Redeploy a broken app to the SAME content with the default flow.
        bad_args = self.create_deploy_args("api", get_api_path("flask-bad"))
        bad_args.extend(["-e", "badapp", "--app-id", guid])
        bad = runner.invoke(cli, bad_args)

        # The command fails because the draft bundle does not start...
        assert bad.exit_code == 1, bad.output
        # ...and crucially, the active bundle is still the working one.
        assert client.content_get(guid)["bundle_id"] == good_bundle_id

    def test_draft_deploy_verifies_the_draft_not_the_active_bundle(self, caplog):
        # #768: with --draft, verification must target the draft bundle, not the
        # currently-active content. Deploying a broken draft over a working active
        # bundle must fail. Without the fix, --draft verified the still-good active
        # content and reported success.
        # Draft deploys (the activate field) require Connect 2025.06.0+.
        require_connect_version("2025.06.0")
        client = RSConnectClient(RSConnectServer(require_connect(), require_api_key()))
        runner = CliRunner()

        # 1. Deploy a working app; it becomes the active bundle.
        with caplog.at_level("INFO"):
            good = runner.invoke(cli, self.create_deploy_args("api", get_api_path("flask")))
        assert good.exit_code == 0, good.output
        guid = self._deployed_content_guid(caplog)
        good_bundle_id = client.content_get(guid)["bundle_id"]

        # 2. Deploy a broken app as a draft to the same content.
        draft_args = self.create_deploy_args("api", get_api_path("flask-bad"))
        draft_args.extend(["-e", "badapp", "--app-id", guid, "--draft"])
        draft = runner.invoke(cli, draft_args)

        # Verification of the broken draft fails...
        assert draft.exit_code == 1, draft.output
        # ...and the draft was never activated, so the active bundle is unchanged.
        assert client.content_get(guid)["bundle_id"] == good_bundle_id

    def test_add_connect(self):
        connect_server = require_connect()
        api_key = require_api_key()
        runner = CliRunner()
        result = runner.invoke(cli, ["add", "--name", "my-connect", "--server", connect_server, "--api-key", api_key])
        assert result.exit_code == 0, result.output
        assert "OK" in result.output

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_add_shinyapps(self):
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)
        try:
            httpretty.register_uri(
                httpretty.GET,
                "https://api.shinyapps.io/v1/users/me",
                body='{"id": 1000}',
                adding_headers={"Content-Type": "application/json"},
                status=200,
            )

            runner = CliRunner()
            result = runner.invoke(
                cli,
                [
                    "add",
                    "--account",
                    "some-account",
                    "--name",
                    "my-shinyapps",
                    "--token",
                    "someToken",
                    "--secret",
                    "c29tZVNlY3JldAo=",
                ],
            )
            assert result.exit_code == 0, result.output
            assert "shinyapps.io credential" in result.output

        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value

    def test_add_name_only_missing_server_and_credentials(self):
        """Regression test: `rsconnect add -n x` should produce a validation error, not a TypeError."""
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)
        try:
            runner = CliRunner()
            result = runner.invoke(
                cli,
                [
                    "add",
                    "--name",
                    "some-name",
                ],
            )
            assert result.exit_code == 1, result.output
            assert "`rsconnect add` requires" in str(result.exception)
        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value

    def test_add_shinyapps_missing_options(self):
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)
        try:
            runner = CliRunner()
            result = runner.invoke(
                cli,
                [
                    "add",
                    "--name",
                    "my-shinyapps",
                    "--token",
                    "someToken",
                ],
            )
            assert result.exit_code == 1, result.output
            assert (
                str(result.exception)
                == "-A/--account, -T/--token, and -S/--secret must all be provided for shinyapps.io. \
See command help for further details."
            )
        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value

    def test_env_management_callback(self):
        ctx = click.Context(cli)

        # env_management is always False when --disable-env-management is True
        ctx.params = {"disable_env_management": True}
        assert env_management_callback(ctx, None, None) is False
        assert env_management_callback(ctx, None, True) is False
        assert env_management_callback(ctx, None, False) is False

        # (env_management == not value) when --disable-env-management is None
        ctx.params = {"disable_env_management": None}
        assert env_management_callback(ctx, None, None) is None
        assert env_management_callback(ctx, None, True) is False
        assert env_management_callback(ctx, None, False) is True


class TestBootstrap(TestCase):
    def setUp(self):
        self.mock_server = "http://localhost:8080"
        self.mock_uri = "http://localhost:8080/__api__/v1/experimental/bootstrap"
        self.jwt_keypath = "tests/testdata/jwt/secret.key"
        self.jwt_env_secret = "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU="

        self.default_cli_args = [
            "bootstrap",
            "--server",
            self.mock_server,
            "--jwt-keypath",
            self.jwt_keypath,
            "--insecure",
        ]

    def create_bootstrap_mock_callback(self, status, json_data):
        def request_callback(request, uri, response_headers):
            # verify auth header is sent correctly
            authorization = request.headers.get("Authorization")
            auth_split = authorization.split(" ")
            self.assertEqual(len(auth_split), 2)
            self.assertEqual(auth_split[0], "Connect-Bootstrap")
            self.assertTrue(has_jwt_structure(auth_split[1]))

            # verify uri
            self.assertEqual(uri, self.mock_uri)

            return [status, {"Content-Type": "application/json"}, json.dumps(json_data)]

        return request_callback

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_bootstrap(self):
        """
        Normal initial-admin operation
        """

        callback = self.create_bootstrap_mock_callback(200, {"api_key": "testapikey123"})

        httpretty.register_uri(
            httpretty.POST,
            self.mock_uri,
            body=callback,
        )

        runner = CliRunner()
        result = runner.invoke(cli, self.default_cli_args)

        self.assertEqual(result.exit_code, 0, result.output)

        json_output = json.loads(result.output)
        expected_output = json.loads(open("tests/testdata/initial-admin-responses/success.json", "r").read())
        self.assertEqual(json_output, expected_output)

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_bootstrap_env_var(self):
        """
        Normal initial-admin operation if secret key is configured using an environment variable
        """
        cli_args = [
            "bootstrap",
            "--server",
            self.mock_server,
            "--insecure",
        ]

        callback = self.create_bootstrap_mock_callback(200, {"api_key": "testapikey123"})

        httpretty.register_uri(
            httpretty.POST,
            self.mock_uri,
            body=callback,
        )

        os.environ[SECRET_KEY_ENV] = self.jwt_env_secret

        runner = CliRunner()
        result = runner.invoke(cli, cli_args)

        self.assertEqual(result.exit_code, 0, result.output)

        json_output = json.loads(result.output)
        expected_output = json.loads(open("tests/testdata/initial-admin-responses/success.json", "r").read())
        self.assertEqual(json_output, expected_output)

        del os.environ[SECRET_KEY_ENV]

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_bootstrap_misc_error(self):
        """
        Fail reasonably if response indicates some non-standard error
        """

        callback = self.create_bootstrap_mock_callback(500, {})

        httpretty.register_uri(
            httpretty.POST,
            self.mock_uri,
            body=callback,
        )

        runner = CliRunner()
        result = runner.invoke(cli, self.default_cli_args)

        self.assertEqual(result.exit_code, 0, result.output)

        json_output = json.loads(result.output)
        expected_output = json.loads(open("tests/testdata/initial-admin-responses/other_error.json", "r").read())
        self.assertEqual(json_output, expected_output)

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_bootstrap_not_found_error(self):
        """
        Fail reasonablly if response indicates 404 not found
        """

        callback = self.create_bootstrap_mock_callback(404, {})

        httpretty.register_uri(
            httpretty.POST,
            self.mock_uri,
            body=callback,
        )

        runner = CliRunner()
        result = runner.invoke(cli, self.default_cli_args)

        self.assertEqual(result.exit_code, 0, result.output)

        json_output = json.loads(result.output)
        expected_output = json.loads(open("tests/testdata/initial-admin-responses/not_found_error.json", "r").read())
        self.assertEqual(json_output, expected_output)

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_bootstrap_forbidden_error(self):
        """
        Fail reasonably if response indicates a forbidden error
        """

        callback = self.create_bootstrap_mock_callback(403, {})

        httpretty.register_uri(
            httpretty.POST,
            self.mock_uri,
            body=callback,
        )

        runner = CliRunner()
        result = runner.invoke(cli, self.default_cli_args)

        self.assertEqual(result.exit_code, 0, result.output)
        json_output = json.loads(result.output)
        expected_output = json.loads(open("tests/testdata/initial-admin-responses/forbidden_error.json", "r").read())

        self.assertEqual(json_output, expected_output)

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_bootstrap_unauthorized(self):
        """
        Fail reasonably if response indicates that request is unauthorized
        """

        callback = self.create_bootstrap_mock_callback(401, {})

        httpretty.register_uri(
            httpretty.POST,
            self.mock_uri,
            body=callback,
        )

        runner = CliRunner()
        result = runner.invoke(cli, self.default_cli_args)

        self.assertEqual(result.exit_code, 0, result.output)

        json_output = json.loads(result.output)
        expected_output = json.loads(open("tests/testdata/initial-admin-responses/unauthorized_error.json", "r").read())

        self.assertEqual(json_output, expected_output)

    def test_bootstrap_help(self):
        """
        Help parameter should complete without erroring
        """

        runner = CliRunner()
        result = runner.invoke(cli, ["bootstrap", "--help"])
        self.assertEqual(result.exit_code, 0, result.output)

    def test_boostrap_invalid_jwt_path(self):
        """
        Fail reasonably if jwt does not exist at provided path
        """

        runner = CliRunner()
        result = runner.invoke(cli, ["bootstrap", "--server", "http://host:port", "--jwt-keypath", "this/is/invalid"])
        self.assertEqual(result.exit_code, 1, result.output)
        self.assertGreater(result.output.find("Error: Keypath does not exist."), -1)

    def test_bootstrap_invalid_server(self):
        """
        Fail reasonably if server URL is formatted incorrectly
        """

        runner = CliRunner()
        result = runner.invoke(cli, ["bootstrap", "--server", "123.some.ip.address", "--jwt-keypath", self.jwt_keypath])
        self.assertEqual(result.exit_code, 1, result.output)
        self.assertGreater(
            result.output.find("Error: Server URL expected to begin with transfer protocol (ex. http/https).\n"), -1
        )

    def test_boostrap_missing_jwt_option(self):
        """
        If jwt keyfile is not specified, it needs to be set using an environment variable
        """
        runner = CliRunner()
        result = runner.invoke(cli, ["bootstrap", "--server", "http://a_server"])
        self.assertEqual(result.exit_code, 1, result.output)
        self.assertGreater(
            result.output.find("Error: Must specify secret key using either a keyfile or environment variable.\n"), -1
        )

    def test_bootstrap_conflicting_jwt_option(self):
        """
        If jwt keyfile is specified, it cannot also be set using an environment variable
        """

        os.environ[SECRET_KEY_ENV] = "a_value"
        runner = CliRunner()
        result = runner.invoke(cli, self.default_cli_args)
        self.assertEqual(result.exit_code, 1, result.output)
        self.assertGreater(
            result.output.find("Error: Cannot specify secret key using both a keyfile and environment variable."), -1
        )

        del os.environ[SECRET_KEY_ENV]

    def test_bootstrap_invalid_env_secret_key(self):
        """
        If jwt env variable is specified, it needs to be a valid base64-encoded value
        """

        os.environ[SECRET_KEY_ENV] = "a_value"
        runner = CliRunner()
        result = runner.invoke(cli, ["bootstrap", "--server", "http://a_server"])
        self.assertEqual(result.exit_code, 1, result.output)
        self.assertGreater(
            result.output.find(
                "Error: Unable to decode base64 data from environment variable: CONNECT_BOOTSTRAP_SECRETKEY\n"
            ),
            -1,
        )

        del os.environ[SECRET_KEY_ENV]

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_bootstrap_raw_output(self):
        """
        Verify we can get the API key as raw output
        """

        expected_api_key = "apikey123"
        callback = self.create_bootstrap_mock_callback(200, {"api_key": expected_api_key})

        httpretty.register_uri(
            httpretty.POST,
            self.mock_uri,
            body=callback,
        )

        runner = CliRunner()
        result = runner.invoke(cli, self.default_cli_args + ["--raw"])

        self.assertEqual(result.exit_code, 0, result.output)

        self.assertEqual(result.output, expected_api_key + "\n")

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_boostrap_raw_output_nonsuccess(self):
        """
        Verify behavior on non-200 response
        """

        callback = self.create_bootstrap_mock_callback(500, {})

        httpretty.register_uri(httpretty.POST, self.mock_uri, body=callback)

        runner = CliRunner()
        result = runner.invoke(cli, self.default_cli_args + ["--raw"])

        self.assertEqual(result.exit_code, 0, result.output)

        self.assertEqual(result.output.find("Error:"), -1)


class TestDeployNodeJS:
    def test_help(self):
        runner = CliRunner()
        result = runner.invoke(cli, ["deploy", "nodejs", "--help"])
        assert result.exit_code == 0
        assert "Node.js application" in result.output
        assert "--entrypoint" in result.output
        assert "--node" in result.output
        assert "--exclude" in result.output
        assert "--disable-env-management-node" in result.output

    def test_missing_directory(self):
        runner = CliRunner()
        result = runner.invoke(cli, ["deploy", "nodejs", "/nonexistent/path"])
        assert result.exit_code != 0

    def test_no_package_json(self, tmp_path):
        (tmp_path / "app.js").write_text("// app")
        runner = CliRunner()
        result = runner.invoke(
            cli,
            ["deploy", "nodejs", "-s", "https://connect.example.com", "-k", "fakekey", str(tmp_path)],
        )
        assert result.exit_code == 1
        assert "package.json" in result.output

    def test_bad_entrypoint(self, tmp_path):
        (tmp_path / "package.json").write_text('{"dependencies":{}}')
        runner = CliRunner()
        result = runner.invoke(
            cli,
            [
                "deploy",
                "nodejs",
                "-s",
                "https://connect.example.com",
                "-k",
                "fakekey",
                "-e",
                "nonexistent.js",
                str(tmp_path),
            ],
        )
        assert result.exit_code == 1
        assert "does not exist" in result.output


class TestWriteManifestNodeJS:
    def test_help(self):
        runner = CliRunner()
        result = runner.invoke(cli, ["write-manifest", "nodejs", "--help"])
        assert result.exit_code == 0
        assert "Node.js application" in result.output
        assert "--entrypoint" in result.output
        assert "--node" in result.output
        assert "--overwrite" in result.output

    def test_missing_directory(self):
        runner = CliRunner()
        result = runner.invoke(cli, ["write-manifest", "nodejs", "/nonexistent/path"])
        assert result.exit_code != 0

    def test_no_package_json(self, tmp_path):
        (tmp_path / "app.js").write_text("// app")
        runner = CliRunner()
        result = runner.invoke(cli, ["write-manifest", "nodejs", str(tmp_path)])
        assert result.exit_code == 1
        assert "package.json" in result.output


class TestWriteManifestExcludeRenv:
    def test_exclude_renv_omits_r_dependencies(self, tmp_path):
        # A valid renv.lock is present but --exclude-renv must keep R dependencies
        # (the manifest "platform"/"packages" keys) out of the manifest entirely.
        content = tmp_path / "fastapi"
        shutil.copytree(get_api_path("stock-api-fastapi", ""), str(content))
        (content / "renv.lock").write_text(
            json.dumps(
                {
                    "R": {
                        "Version": "4.3.1",
                        "Repositories": [{"Name": "CRAN", "URL": "https://cloud.r-project.org"}],
                    },
                    "Packages": {
                        "R6": {"Package": "R6", "Version": "2.5.1", "Source": "Repository", "Repository": "CRAN"},
                    },
                }
            )
        )

        runner = CliRunner()
        result = runner.invoke(
            cli, ["write-manifest", "fastapi", str(content), "--entrypoint", "main", "--exclude-renv"]
        )
        assert result.exit_code == 0, result.output

        manifest = json.loads((content / "manifest.json").read_text())
        assert "platform" not in manifest
        assert "packages" not in manifest


class TestDefaultServer:
    def test_list_shows_default_marker(self, tmp_path):
        from rsconnect.metadata import ServerStore

        store = ServerStore(base_dir=str(tmp_path))
        store.set("s1", "http://s1.local", api_key="key1", set_as_default=True)
        store.set("s2", "http://s2.local", api_key="key2")

        runner = CliRunner()
        with mock.patch("rsconnect.main.server_store", store):
            result = runner.invoke(cli, ["list"])
        assert result.exit_code == 0, result.output
        assert "[default]" in result.output
        assert "s1" in result.output

    def test_list_no_default_marker(self, tmp_path):
        from rsconnect.metadata import ServerStore

        store = ServerStore(base_dir=str(tmp_path))
        store.set("s1", "http://s1.local", api_key="key1")

        runner = CliRunner()
        with mock.patch("rsconnect.main.server_store", store):
            result = runner.invoke(cli, ["list"])
        assert result.exit_code == 0, result.output
        assert "[default]" not in result.output

    def test_remove_default_shows_note(self, tmp_path):
        from rsconnect.metadata import ServerStore

        store = ServerStore(base_dir=str(tmp_path))
        store.set("s1", "http://s1.local", api_key="key1", set_as_default=True)
        store.set("s2", "http://s2.local", api_key="key2")

        runner = CliRunner()
        with mock.patch("rsconnect.main.server_store", store):
            result = runner.invoke(cli, ["remove", "--name", "s1"])
        assert result.exit_code == 0, result.output
        assert "was the default" in result.output

    def test_remove_non_default_no_note(self, tmp_path):
        from rsconnect.metadata import ServerStore

        store = ServerStore(base_dir=str(tmp_path))
        store.set("s1", "http://s1.local", api_key="key1", set_as_default=True)
        store.set("s2", "http://s2.local", api_key="key2")

        runner = CliRunner()
        with mock.patch("rsconnect.main.server_store", store):
            result = runner.invoke(cli, ["remove", "--name", "s2"])
        assert result.exit_code == 0, result.output
        assert "was the default" not in result.output

    @httpretty.activate(verbose=True, allow_net_connect=False)
    def test_add_set_default(self, tmp_path):
        from rsconnect.metadata import ServerStore

        httpretty.register_uri(
            httpretty.GET,
            "http://connect.local/__api__/server_settings",
            body='{"version": "2024.01.0"}',
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )
        httpretty.register_uri(
            httpretty.GET,
            "http://connect.local/__api__/v1/user",
            body='{"username": "admin"}',
            adding_headers={"Content-Type": "application/json"},
            status=200,
        )

        store = ServerStore(base_dir=str(tmp_path))
        original_api_key_value = os.environ.pop("CONNECT_API_KEY", None)
        original_server_value = os.environ.pop("CONNECT_SERVER", None)
        try:
            runner = CliRunner()
            with mock.patch("rsconnect.main.server_store", store):
                result = runner.invoke(
                    cli,
                    [
                        "add",
                        "--name",
                        "myserver",
                        "--server",
                        "http://connect.local",
                        "--api-key",
                        "fake-key",
                        "--set-default",
                    ],
                )
            assert result.exit_code == 0, result.output
            assert "is now the default" in result.output
            assert store.get_default() is not None
            assert store.get_default()["name"] == "myserver"
        finally:
            if original_api_key_value:
                os.environ["CONNECT_API_KEY"] = original_api_key_value
            if original_server_value:
                os.environ["CONNECT_SERVER"] = original_server_value


class TestDeployGit(TestCase):
    """Tests for deploy git CLI command."""

    def test_deploy_git_help(self):
        """Test that deploy git --help works."""
        runner = CliRunner()
        result = runner.invoke(cli, ["deploy", "git", "--help"])
        assert result.exit_code == 0, result.output
        assert "Deploy content to Posit Connect directly from a remote Git repository" in result.output
        assert "--repository" in result.output
        assert "--branch" in result.output
        assert "--subdirectory" in result.output

    def test_deploy_git_requires_repository(self):
        """Test that --repository is required."""
        runner = CliRunner()
        result = runner.invoke(cli, ["deploy", "git", "-s", "http://example.com", "-k", "key"])
        assert result.exit_code != 0
        assert "Missing option" in result.output or "required" in result.output.lower()

    def test_deploy_git_rejects_new_and_app_id_together(self):
        """Test that --new and --app-id are mutually exclusive."""
        runner = CliRunner()
        result = runner.invoke(
            cli,
            [
                "deploy",
                "git",
                "-s",
                "http://example.com",
                "-k",
                "key",
                "--repository",
                "https://github.com/user/repo",
                "--new",
                "--app-id",
                "some-guid",
            ],
        )
        assert result.exit_code != 0
        assert "mutually exclusive" in result.output.lower()


class TestGenerateGitTitle:
    """Tests for _generate_git_title helper function."""

    def test_simple_repo_url(self):
        from rsconnect.main import _generate_git_title

        result = _generate_git_title("https://github.com/user/myrepo", "")
        assert result == "myrepo"

    def test_repo_url_with_git_suffix(self):
        from rsconnect.main import _generate_git_title

        result = _generate_git_title("https://github.com/user/myrepo.git", "")
        assert result == "myrepo"

    def test_repo_with_subdirectory(self):
        from rsconnect.main import _generate_git_title

        result = _generate_git_title("https://github.com/user/myrepo", "apps/dashboard")
        assert result == "myrepo/apps/dashboard"

    def test_repo_with_subdirectory_leading_slash(self):
        from rsconnect.main import _generate_git_title

        result = _generate_git_title("https://github.com/user/myrepo", "/apps/dashboard/")
        assert result == "myrepo/apps/dashboard"

    def test_repo_with_root_subdirectory(self):
        from rsconnect.main import _generate_git_title

        result = _generate_git_title("https://github.com/user/myrepo", "/")
        assert result == "myrepo"

    def test_repo_url_with_trailing_slash(self):
        from rsconnect.main import _generate_git_title

        result = _generate_git_title("https://github.com/user/myrepo/", "subdir")
        assert result == "myrepo/subdir"
