"""The ``.posit/publish/deployments/<name>.toml`` record (the "where").

A record ties a config to a specific destination: the ``server_url`` (which
resolves to saved credentials), the content ``id`` (GUID) to redeploy in place,
the dashboard/direct/logs URLs, the bundle id, and a full embedded snapshot of
the config that was deployed. rsconnect also stores the concrete ``files`` and
``requirements`` that went into the bundle.
"""

from __future__ import annotations

import dataclasses
import json
import os
import tarfile
import typing
from datetime import datetime, timezone

from .. import VERSION
from . import config as config_mod
from . import schema, serialize

_AUTOGEN_HEADER = "# This file is automatically generated by rsconnect-python; do not edit."

# Keys rsconnect manages; anything else on disk is preserved via ``extra``.
_MANAGED_KEYS = frozenset(
    {
        "$schema",
        "server_type",
        "server_url",
        "client_version",
        "created_at",
        "type",
        "configuration_name",
        "id",
        "dashboard_url",
        "direct_url",
        "logs_url",
        "deployed_at",
        "bundle_id",
        "bundle_url",
        "files",
        "requirements",
        "configuration",
        "connect_cloud",
    }
)


@dataclasses.dataclass
class PublisherRecord:
    """A parsed / to-be-written deployment record."""

    server_url: str = ""
    server_type: str = schema.PRODUCT_TYPE_CONNECT
    id: typing.Optional[str] = None
    type: str = "unknown"
    configuration_name: typing.Optional[str] = None
    created_at: typing.Optional[str] = None
    deployed_at: typing.Optional[str] = None
    client_version: typing.Optional[str] = None
    dashboard_url: typing.Optional[str] = None
    direct_url: typing.Optional[str] = None
    logs_url: typing.Optional[str] = None
    bundle_id: typing.Optional[str] = None
    bundle_url: typing.Optional[str] = None
    files: typing.List[str] = dataclasses.field(default_factory=list)
    requirements: typing.List[str] = dataclasses.field(default_factory=list)
    configuration: typing.Optional[typing.Dict[str, typing.Any]] = None
    # Connect Cloud settings ({account_name}), preserved for interop with
    # Publisher-authored records.
    connect_cloud: typing.Optional[typing.Dict[str, typing.Any]] = None
    schema_url: str = schema.RECORD_SCHEMA_URL
    extra: typing.Dict[str, typing.Any] = dataclasses.field(default_factory=dict)

    def config(self) -> typing.Optional[config_mod.PublisherConfig]:
        """The embedded ``[configuration]`` snapshot as a :class:`PublisherConfig`."""
        if self.configuration is None:
            return None
        return config_mod.from_dict(self.configuration)

    def to_dict(self) -> typing.Dict[str, typing.Any]:
        """Render to an ordered dict ready for TOML serialization."""
        data: typing.Dict[str, typing.Any] = {}
        data["$schema"] = self.schema_url or schema.RECORD_SCHEMA_URL
        data["server_type"] = self.server_type or schema.PRODUCT_TYPE_CONNECT
        data["server_url"] = self.server_url
        data["client_version"] = self.client_version or VERSION
        data["created_at"] = self.created_at or now()
        data["type"] = self.type
        if self.configuration_name:
            data["configuration_name"] = self.configuration_name
        if self.id:
            data["id"] = self.id
        if self.dashboard_url:
            data["dashboard_url"] = self.dashboard_url
        if self.direct_url:
            data["direct_url"] = self.direct_url
        if self.logs_url:
            data["logs_url"] = self.logs_url
        if self.deployed_at:
            data["deployed_at"] = self.deployed_at
        if self.bundle_id:
            data["bundle_id"] = self.bundle_id
        if self.bundle_url:
            data["bundle_url"] = self.bundle_url
        if self.files:
            data["files"] = list(self.files)
        if self.requirements:
            data["requirements"] = list(self.requirements)
        if self.connect_cloud:
            data["connect_cloud"] = self.connect_cloud
        if self.configuration:
            data["configuration"] = self.configuration
        for key, value in self.extra.items():
            data.setdefault(key, value)
        return data


def now() -> str:
    """Current time as an RFC 3339 / ISO 8601 string, matching Publisher."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def from_dict(data: typing.Mapping[str, typing.Any]) -> PublisherRecord:
    """Build a :class:`PublisherRecord` from an already-parsed mapping."""
    return PublisherRecord(
        server_url=data.get("server_url", ""),
        server_type=data.get("server_type", schema.PRODUCT_TYPE_CONNECT),
        id=data.get("id"),
        type=data.get("type", "unknown"),
        configuration_name=data.get("configuration_name"),
        created_at=data.get("created_at"),
        deployed_at=data.get("deployed_at"),
        client_version=data.get("client_version"),
        dashboard_url=data.get("dashboard_url"),
        direct_url=data.get("direct_url"),
        logs_url=data.get("logs_url"),
        bundle_id=data.get("bundle_id"),
        bundle_url=data.get("bundle_url"),
        files=list(data.get("files", []) or []),
        requirements=list(data.get("requirements", []) or []),
        configuration=data.get("configuration"),
        connect_cloud=data.get("connect_cloud"),
        schema_url=data.get("$schema", schema.RECORD_SCHEMA_URL),
        extra={k: v for k, v in data.items() if k not in _MANAGED_KEYS},
    )


def read_record(path: str) -> PublisherRecord:
    """Parse a deployment record file into a :class:`PublisherRecord`."""
    return from_dict(serialize.load(path))


def write_record(project_dir: str, name: str, record: PublisherRecord) -> str:
    """Write ``record`` to ``.posit/publish/deployments/<name>.toml``.

    Preserves ``created_at``, ``bundle_url``, and any unmanaged fields from an
    existing record.
    """
    path = schema.record_path(project_dir, name)
    if os.path.exists(path):
        existing = read_record(path)
        if not record.created_at:
            record.created_at = existing.created_at
        if not record.bundle_url:
            record.bundle_url = existing.bundle_url
        record.extra = {**existing.extra, **record.extra}
    serialize.write(path, serialize.dumps(record.to_dict(), [_AUTOGEN_HEADER]))
    return path


def discover_records(project_dir: str) -> typing.List[str]:
    """Return the paths of all record files under ``deployments`` (sorted)."""
    directory = schema.deployments_dir(project_dir)
    if not os.path.isdir(directory):
        return []
    return sorted(
        os.path.join(directory, f)
        for f in os.listdir(directory)
        if f.endswith(".toml") and os.path.isfile(os.path.join(directory, f))
    )


# --- reading content details back out of a built bundle --------------------


def _parse_requirements(content: str) -> typing.List[str]:
    """Return non-blank, non-comment lines of a requirements file."""
    out: typing.List[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            out.append(stripped)
    return out


def _read_member(tar: tarfile.TarFile, name: str) -> typing.Optional[str]:
    try:
        member = tar.extractfile(name)
    except KeyError:
        return None
    if member is None:
        return None
    return member.read().decode("utf-8")


@dataclasses.dataclass
class BundleContentDetails:
    """Content facts recovered from a built bundle's ``manifest.json``."""

    entrypoint: str = ""
    files: typing.List[str] = dataclasses.field(default_factory=list)
    requirements: typing.List[str] = dataclasses.field(default_factory=list)
    python: typing.Optional[typing.Dict[str, typing.Any]] = None
    quarto: typing.Optional[typing.Dict[str, typing.Any]] = None


def _recover_entrypoint_path(entrypoint: str, files: typing.Sequence[str]) -> str:
    """Resolve a bare Python module reference back to its literal file path.

    rsconnect-python's own Python deploys record ``metadata.entrypoint`` as an
    importable module reference rather than a path -- e.g. ``"app"`` (or
    ``"app:app"``) for ``app.py``. Posit Publisher's schema documents
    ``entrypoint`` as "Name of the primary file containing the content", and its
    own detectors (``pyshiny.ts``, ``pythonApp.ts``) always record the literal
    filename for Flask/FastAPI/Dash/Shiny; only Shiny Express writes a
    ``module:object`` reference, and that module never names a real file. So
    recovering the literal path here, when the manifest confirms it exists,
    matches what Publisher itself would write -- a config a human (or Publisher)
    can act on, not an rsconnect-internal module name.
    """
    if not entrypoint or entrypoint.endswith(".py"):
        return entrypoint
    module = entrypoint.split(":", 1)[0]
    candidate = module + ".py"
    return candidate if candidate in files else entrypoint


def details_from_manifest(manifest: typing.Mapping[str, typing.Any]) -> BundleContentDetails:
    """Parse content facts out of a ``manifest.json`` dict.

    Recovers the file list, entrypoint, and Python/Quarto settings. Requirements
    are not populated here (they live in a separate package file, not in the
    manifest); :func:`read_bundle_details` fills them from the bundle.
    """
    details = BundleContentDetails()
    details.files = sorted((manifest.get("files") or {}).keys())
    meta = manifest.get("metadata") or {}
    entrypoint = meta.get("entrypoint")
    if entrypoint:
        details.entrypoint = _recover_entrypoint_path(entrypoint, details.files)
    else:
        # primary_rmd/primary_html are always literal paths already.
        details.entrypoint = meta.get("primary_rmd") or meta.get("primary_html") or ""

    mpy = manifest.get("python")
    if mpy:
        pm = mpy.get("package_manager") or {}
        pkg_file = pm.get("package_file")
        python: typing.Dict[str, typing.Any] = {}
        if mpy.get("version"):
            python["version"] = mpy["version"]
        if pkg_file:
            python["package_file"] = pkg_file
        if pm.get("name"):
            python["package_manager"] = pm["name"]
        requires = ((manifest.get("environment") or {}).get("python") or {}).get("requires")
        if requires:
            python["requires_python"] = requires
        details.python = python or None

    mq = manifest.get("quarto")
    if mq:
        quarto: typing.Dict[str, typing.Any] = {}
        if mq.get("version"):
            quarto["version"] = mq["version"]
        if mq.get("engines"):
            quarto["engines"] = mq["engines"]
        details.quarto = quarto or None
    return details


def read_bundle_details(bundle: typing.IO[bytes]) -> BundleContentDetails:
    """Extract entrypoint, files, requirements and language settings from a bundle.

    The bundle is a ``.tar.gz`` whose ``manifest.json`` lists the deployed files
    (keyed by project-relative path) and points at the Python package file.
    Requirements are read from that file's contents inside the tarball.

    The caller is responsible for treating failures as non-fatal.
    """
    details = BundleContentDetails()
    bundle.seek(0)
    try:
        with tarfile.open(fileobj=bundle, mode="r:gz") as tar:
            raw = _read_member(tar, "manifest.json")
            if raw is None:
                return details
            manifest = json.loads(raw)
            details = details_from_manifest(manifest)
            pkg_file = (details.python or {}).get("package_file")
            if pkg_file:
                content = _read_member(tar, pkg_file)
                if content is not None:
                    details.requirements = _parse_requirements(content)
    finally:
        bundle.seek(0)
    return details
