#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o xtrace

[[ "${PYTHON_VERSION}" ]] || {
  : WARNING: this script is intended to be run inside a docker python container
  exit 1
}
python -m pip install --upgrade pip
pip install -r requirements.txt
