#!/usr/bin/env bash
set -o errexit
set -o pipefail

main() {
  set -o xtrace

  local top
  top="$(git rev-parse --show-toplevel)"

  local pipenv_requires="${top}/.pipenv-requires"

  pipenv install --dev
  _print_pipfile_packages >"${pipenv_requires}"
  pipenv run pip install -U --pre -r "${pipenv_requires}"
  rm -f "${pipenv_requires}"
}

_print_pipfile_packages() {
  pipenv run python <<PYTHON
import toml

for package in toml.load(open("${top}/Pipfile")).get("packages").keys():
    print(package)
PYTHON
}

main "${@}"
