#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o xtrace

: "${PYTEST_ARGS:=-vv --cov=rsconnect --cov-report=term --cov-report=html}"
pytest ${PYTEST_ARGS} --mypy ./tests/test_main_content.py
