name: preview docs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_dispatch:

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          version: ">=0.9.0"

      - uses: extractions/setup-just@v3

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install and Build
        if: github.event.action != 'closed' # skip the build if the PR has been closed
        run: just docs

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./great-docs/_site/
